"""empty message

Revision ID: 68b8541fc9de
Revises: 6fb9095404b6
Create Date: 2020-06-05 19:16:27.191398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b8541fc9de'
down_revision = '6fb9095404b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('venue_description', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'venue_description')
    # ### end Alembic commands ###
