"""empty message

Revision ID: 94d6be48c626
Revises: 
Create Date: 2020-05-26 22:42:05.270907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d6be48c626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('seeking', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking')
    op.drop_column('Venue', 'genre')
    op.drop_table('Shows')
    # ### end Alembic commands ###
