"""empty message

Revision ID: b2baed304e1b
Revises: 51cc3bd0f78e
Create Date: 2020-05-27 23:19:10.454794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2baed304e1b'
down_revision = '51cc3bd0f78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('talent_description', sa.String(length=500), nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'talent_description')
    # ### end Alembic commands ###
